### ISSUE TITLE
Building `yay` fails

### ISSUE THREAD

**Issue by thomaseizinger** [edlanglois/pkgbuild-action#9]
I recently started hitting the following error in my GitHub workflows: 

```
==> Starting build()...
pacman-git
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=11.1.2" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: downloading github.com/Jguer/go-alpm/v2 v2.1.1
go: downloading github.com/Jguer/aur v1.0.1
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20210502114700-cff030e927a5
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
go: downloading github.com/leonelquinteros/gotext v1.5.0
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go: downloading golang.org/x/sys v0.0.0-20220204135822-1c1b9b1eba6a
go: downloading golang.org/x/text v0.3.7
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
make: *** [Makefile:112: yay] Error 1
```

Here is one of the failing workflows: https://github.com/thomaseizinger/pkgbuilds/runs/6536807072

Do you have any advice on how to fix this?
I've also found that there is a [`yay-bin`](https://aur.archlinux.org/packages/yay-bin) package?

Using that one would - I presume - fix this error and also reduce CI runtime slightly because we don't have to re-build yay on every run.

**Comment by goggle** [comment]
I run into the same issue: https://github.com/goggle/aur/actions/runs/2944043617/jobs/4702214794

**Comment by edlanglois** [comment]
I switched to yay-bin in the latest release, fixing it. Thanks for the suggestion!
